apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/xMADAN05/xLab.git'
      revision: HEAD
      directories:
      - path: applications/apps/*/overlays/dev
      requeueAfterSeconds: 300 # wait 5 min before scans
  template:
    metadata:
      name: '{{ index (split .path.path "/") 2 }}-dev'
    spec:
      project: default
      # Application manifest source
      source:
        repoURL: 'https://github.com/xMADAN05/xLab.git'
        targetRevision: HEAD
        path: '{{ .path.path }}'
        kustomize:
          enableHelm: true
      destination:
        server: https://kubernetes.default.svc
        # namespace: 'apps-dev' # Namespace defined in kustomization 
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true