apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
    repoURL: 'https://github.com/xMADAN05/gitops-homelab.git'
    revision: HEAD
    directories:
    - path: apps/*/dev
  template:
    metadata:
      name: '{{index .path.segments 1}}'
      spec:
        project: default
        # Application manifest source
        source:
          repoURL: 'https://github.com/xMADAN05/gitops-homelab.git'
          targetRevision: HEAD
          path: '{{.path.path}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: 'argocd'
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            prune: true
            selfHeal: true