
namespace: default
createNamespace: true

replicaCount: 1

image:
  repository: ""  # override per app
  tag: ""  # override per app
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

readinessProbe:
  enabled: true
  path: /ready
  port: http
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: http
  initialDelaySeconds: 15
  periodSeconds: 20

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: ""
  path: "/"
  pathType: Prefix
  ingressClassName: kong
  annotations: {}
  tls: []

persistence:
  enabled: false
  size: 10Gi
  storageClass: longhorn

config:
  enabled: false
  data: {}

env: []
containerPorts:
  - name: http
    containerPort: 80

nodeSelector: {}
tolerations: []
affinity: {}
